[package]
name = "rusty-yaml"
version = "0.4.3"
authors = ["adam-mcdaniel <adam.mcdaniel17@gmail.com>"]
edition = "2018"
description = "A rust library to parse yaml files"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
yaml-rust="0.4.3"
